jobhub/urls.py
from django.urls import path
from jobhub import views

urlpatterns = [
    path("login/", views.login, name="login"),
    path("register/", views.register, name="register"),
    path("other_company_profile/", views.other_company_profile, name="other_company_profile"),
    path("other_user_profile/", views.other_user_profile, name="other_user_profile"),

    path("joblist/", views.joblist,name='joblist'),
    path("joblist/getlist", views.joblist_getlist,name='joblist_getlist'),
    path("joblist/getdetail", views.joblist_getdetail,name='joblist_getdetail'),
    path("joblist/search", views.joblist_search,name='joblist_search'),

    path("joblist/submit", views.joblist_submit_application,name='joblist_submit'),
    path("joblist/withdraw", views.joblist_withdraw_application,name='joblist_withdraw'),

    path("base_user_profile/", views.base_user_profile, name="base_user_profile"),
    path("base_company_profile/", views.base_company_profile, name="base_company_profile"),
    path("delete_experience/", views.delete_experience, name="delete_experience"),
    path("delete_staff/", views.delete_staff, name="delete_staff"),
    path("delete_review/", views.delete_review, name="delete_review"),

    path('applicant_application/<str:filter_by>/', views.a_application, name='applicant_application'),
    path('applicant_application/get-application/<str:filter_by>/', views.get_application, name='get-application'),
    path("employer_application/<int:id>/<str:filter_by>/", views.e_application, name="employer_application"),
    path('employer_application/get-applicant/<int:id>/<str:filter_by>/', views.get_applicant, name='get-applicant'),
    path('update_application_status/', views.update_application_status, name='update_application_status'),
    
    path("logout/", views.logout_action, name="logout"),
]

webapps/urls.py
from django.contrib import admin
from django.urls import path,include
from jobhub import views
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", views.home),
    path("", include('jobhub.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

jobhub/models.py
from django.db import models
from django.contrib.auth.models import User

# ================== User Profile ==================
class PersonalInfo(models.Model):
    name = models.CharField(max_length=255, blank=False)
    position = models.CharField(max_length=255, blank=True)
    company_name = models.CharField(max_length=255, blank=True)
    company_id = models.IntegerField(blank=True, null=True)
    school = models.CharField(max_length=255, blank=True)
    bio = models.TextField(blank=True)

    def __str__(self):
        return self.name + " - " + self.position + " - " + self.bio

from django.core.validators import FileExtensionValidator
class ContactInfo(models.Model):
    phone = models.CharField(max_length=12, blank=True)
    email = models.EmailField(blank=False)
    address = models.TextField(blank=True)
    linkedin = models.URLField(blank=True)
    resume = models.FileField(upload_to='resumes/', blank=True, validators=[FileExtensionValidator(allowed_extensions=['pdf'])])

    def __str__(self):
        return self.email + " - " + self.phone + " - " + self.address + " - " + self.linkedin

class OtherInfo(models.Model):
    skills = models.TextField(blank=True)
    interests = models.TextField(blank=True)

    def __str__(self):
        return self.skills + " - " + self.interests

class Education(models.Model):
    school = models.CharField(max_length=255, blank=False)
    major = models.CharField(max_length=255, blank=False)
    gpa = models.DecimalField(max_digits=3, decimal_places=2, blank=True, null=True)
    start_time = models.DateField(blank=False)
    end_time = models.DateField(blank=True, null=True)
    location = models.CharField(max_length=255, blank=False)
    description = models.TextField(blank=True)
    
    def __str__(self):
        return self.school + " - " + self.major + " - " + self.location + " - " + self.description

class WorkExperience(models.Model):
    company = models.CharField(max_length=255, blank=False)
    role = models.CharField(max_length=255, blank=False)
    start_time = models.DateField(blank=False)
    end_time = models.DateField(blank=True, null=True)
    type = models.CharField(max_length=100, blank=False)
    location = models.CharField(max_length=255, blank=False)
    description = models.TextField(blank=True)

    def __str__(self):
        return self.company + " - " + self.role + " - " + self.type + " - " + self.location + " - " + self.description
    
class ProjectExperience(models.Model):
    project_name = models.CharField(max_length=255, blank=False)
    role = models.CharField(max_length=255, blank=True)
    start_time = models.DateField(blank=False)
    end_time = models.DateField(blank=True, null=True)
    location = models.CharField(max_length=255, blank=False)
    description = models.TextField(blank=True)

    def __str__(self):
        return self.project_name + " - " + self.role + " - " + self.location + " - " + self.description

class UserProfile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    personal_info = models.OneToOneField(PersonalInfo, on_delete=models.CASCADE)
    contact_info = models.OneToOneField(ContactInfo, on_delete=models.CASCADE)
    other_info = models.OneToOneField(OtherInfo, on_delete=models.CASCADE)
    education = models.ManyToManyField(Education)
    work_experience = models.ManyToManyField(WorkExperience)
    project_experience = models.ManyToManyField(ProjectExperience)
    picture = models.ImageField(upload_to="profile_pictures", blank=True)


    def __str__(self):
        return self.user.username + " - " + self.personal_info.name + " - " + self.contact_info.email + " - " + self.other_info.skills

# ==================  Company Profile  ==================    
class CompanyInfo(models.Model):
    name = models.CharField(max_length=255, blank=False)
    bio = models.TextField(blank=True)
    industry = models.CharField(max_length=255, blank=True)
    size = models.CharField(max_length=255, blank=True)

    def __str__(self):
        return self.name + " - " + self.bio + " - " + self.industry + " - " + self.size

class CompanyContactInfo(models.Model):
    company = models.OneToOneField(CompanyInfo, on_delete=models.CASCADE)
    phone = models.CharField(max_length=12, blank=True)
    email = models.EmailField(blank=False)
    address = models.TextField(blank=True)
    website = models.URLField(blank=True)
    linkedin = models.URLField(blank=True)

    def __str__(self):
        return self.company.name + " - " + self.email + " - " + self.phone + " - " + self.address + " - " + self.website + " - " + self.linkedin

class CompanyReview(models.Model):
    company = models.ForeignKey(CompanyInfo, on_delete=models.CASCADE)
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    time_posted = models.DateTimeField(auto_now_add=True)
    # // overall rating is the average of the following ratings, which is round 1
    overall_rating = models.DecimalField(max_digits=3, decimal_places=1, blank=False)
    interview_progression_rating = models.DecimalField(max_digits=3, decimal_places=1, blank=False)
    application_response_time_rating = models.DecimalField(max_digits=3, decimal_places=1, blank=False)
    benefits_during_interview_rating = models.DecimalField(max_digits=3, decimal_places=1, blank=False)
    interview_atmosphere_rating = models.DecimalField(max_digits=3, decimal_places=1, blank=False)
    interview_etiquette_rating = models.DecimalField(max_digits=3, decimal_places=1, blank=False)
    five_star_rating = models.IntegerField(blank=False)
    four_star_rating = models.IntegerField(blank=False)
    three_star_rating = models.IntegerField(blank=False)
    two_star_rating = models.IntegerField(blank=False)
    one_star_rating = models.IntegerField(blank=False)

    def __str__(self):
        # return self.company.name + " - " + self.user.username + " - " + self.time_posted + " - " + self.overall_rating + " - " + self.interview_progression_rating + " - " + self.application_response_time_rating + " - " + self.benefits_during_interview_rating + " - " + self.interview_atmosphere_rating + " - " + self.interview_etiquette_rating + " - " + self.five_star_rating + " - " + self.four_star_rating + " - " + self.three_star_rating + " - " + self.two_star_rating + " - " + self.one_star_rating
        return self.company.name + " - " + self.user.username + " - " + self.time_posted + " - " + self.overall_rating + " - " + self.interview_progression_rating + " - " + self.application_response_time_rating + " - " + self.benefits_during_interview_rating + " - " + self.interview_atmosphere_rating + " - " + self.interview_etiquette_rating + " - " + self.five_star_rating + " - " + self.four_star_rating + " - " + self.three_star_rating + " - " + self.two_star_rating + " - " + self.one_star_rating + " - " + self.review

class IndividualReview(models.Model):
    title = models.CharField(max_length=255, blank=False)
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    role = models.CharField(max_length=255, blank=False)
    time_posted = models.DateTimeField(auto_now_add=True)
    overall_rating = models.IntegerField(blank=False)
    interview_progression_rating = models.IntegerField(blank=False)
    application_response_time_rating = models.IntegerField(blank=False)
    benefits_during_interview_rating = models.IntegerField(blank=False)
    interview_atmosphere_rating = models.IntegerField(blank=False)
    interview_etiquette_rating = models.IntegerField(blank=False)
    review = models.TextField(blank=True)

    def __str__(self):
        return self.title + " - " + self.user.username + " - " + self.time_posted + " - " + self.overall_rating + " - " + self.interview_progression_rating + " - " + self.application_response_time_rating + " - " + self.benefits_during_interview_rating + " - " + self.interview_atmosphere_rating + " - " + self.interview_etiquette_rating + " - " + self.review

class CompanyProfile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE, related_name='company_profile')
    company_info = models.OneToOneField(CompanyInfo, on_delete=models.CASCADE)
    company_contact_info = models.OneToOneField(CompanyContactInfo, on_delete=models.CASCADE)
    company_review = models.OneToOneField(CompanyReview, on_delete=models.CASCADE)
    individual_reviews = models.ManyToManyField(IndividualReview)
    public_staff_list = models.ManyToManyField(UserProfile)
    picture = models.ImageField(upload_to="profile_pictures", blank=True)

    def __str__(self):
        return self.company_info.name + " - " + self.company_contact_info.email + " - " + self.company_contact_info.phone + " - " + self.company_contact_info.address + " - " + self.company_contact_info.website + " - " + self.company_contact_info.linkedin
    

# ==================  Job List  ==================

class JobSummary(models.Model):
    job_type = models.CharField(max_length=255, blank=True)
    post_time = models.DateField(blank=False)
    due_time = models.DateField(blank=False)
    location = models.CharField(max_length=255, blank=True)
    estimate_pay_lower = models.PositiveIntegerField(blank=False)
    estimate_pay_upper = models.PositiveIntegerField(blank=False)
    note = models.CharField(max_length=255, blank=True)

    def __str__(self):
        return f"Posted: {self.post_time} - Due: {self.due_time} - Location: {self.location}"

class JobHighlight(models.Model):
    content = models.CharField(max_length=1023, blank=True)
    def __str__(self):
        # Truncate content to a reasonable length for display
        return f"Highlight: {self.content[:50]}..." if len(self.content) > 50 else self.content

class JobDetail(models.Model):
    content = models.CharField(max_length=1023, blank=True)
    def __str__(self):

jobhub/templates/jobhub/base_company_profile.html
<!doctype html>
<html lang="en">

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title> {% block title %} JobHub {% endblock %} </title>
    <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>

    {% load static %}
    <link rel="stylesheet" href="{% static 'jobhub/pure-min.css' %}">
    <link rel="stylesheet" href="{% static 'jobhub/profile_style.css' %}">
    <link rel="stylesheet" href="{% static 'jobhub/grids-responsive-min.css' %}">
    <!-- from static import profile.js -->
    <script src="{% static 'jobhub/profile.js' %}"></script>
</head>

<body data-form-type="{{ form_type }}">
    {% block content %}
    <div id="layout">
        
        <div id="menu">
            <div id="nav">
                <div class="nav-inner">
                    <img width="100" height="100" alt="Tilo Mitra&#x27;s avatar" class="jobhub-avatar" src="/static/jobhub/jobhub.jpg">
                    <p> {{ user.last_name }} account</p>
                    <div class="pure-menu">
                        <ul class="pure-menu-list">
                            <li><a href="{% url 'base_company_profile' %}" class="pure-menu-link">My Profile</a></li>
                            <li><a href="{% url 'joblist' %}" class="pure-menu-link">Jobs</a></li>
                            {% if user.last_name == 'employer' %}
                                <li><a href="{% url 'employer_application' 0 'all' %}" class="pure-menu-link">Applications</a></li>
                            {% else %}
                                <li><a href="{% url 'applicant_application' 'all' %}" class="pure-menu-link">Applications</a></li>
                            {% endif %}                        
                        </ul>
                    </div>
                    <a href="{% url 'logout' %}" class="pure-menu-link logout-btn">Logout</a>
                </div>
            </div>
        </div>

        <div id="main">
            <div class="header">
                <h1>{{ profile.company_info.name }} </h1>
                <h2>
                    Employer Username: <span id="userId">{{ profile.user.username }}</span>
                    <i class="copy-icon" id="copyButton" title="Copy User ID" onclick="copyUserId()"> ✂ </i>
                </h2>
            </div>

            <div class="content">
                <div class="pure-g">
                    <!-- left part -->
                    <div class="pure-u-1 pure-u-md-1-3">
                        <!-- basic info card -->
                        {% include "jobhub/company_profile/profile_company_info.html" %}

                        <!-- contact info card -->
                        {% include "jobhub/company_profile/profile_company_contact_info.html" %}

                        <!-- jobs card -->
                        <div class="card">
                            <h3>Jobs Opening</h3>
                            {% for job in jobs %}
                            <p><a href="/joblist/?id={{job.id}}">{{ job.name }}</a>
                                <span class="job-location">{{ job.summary.location }}</span>
                            </p>
                            {% endfor %}
                            {% if jobs|length == 0 %}
                            <p>No jobs opening</p>
                            {% endif %}
                            <a class="pure-button" 
                                href="/joblist/?company_id={{profile.id}}">See All ></a> 
                        </div>

                        <!-- staff card -->
                        {% include "jobhub/company_profile/profile_staff_list.html" %}
                    </div>

                    <!-- right part -->
                    <div class="pure-u-1 pure-u-md-2-3">
                        <!-- Review Section -->
                        <h2 class="content-subhead-right">Company Reviews</h2>

                        <!-- Overall Rating Card -->
                        {% include "jobhub/company_profile/profile_overall_rating.html" %}

                        <!-- Individual Review Cards -->
                        <h2 class="content-subhead-right">Individual Interview Reviews (2)</h2>

                        <div class="card">
                            <div class="filter-container">
                                <!-- Job Title Filter -->
                                <div class="filter-item">
                                    <label for="job-title">Job Title:</label>
                                    <!-- when select, call this func filterIndividualReviews -->
                                    <select id="job-title" onchange="filterIndividualReviews()">
                                        <option selected value="all">All</option>
                                        <option value="IT Intern">IT Intern</option>
                                        <option value="Software Engineer">Software Engineer</option>
                                        <option value="Product Manager">Product Manager</option>
                                        <option value="Product Designer">Machine Learning Engineer</option>
                                        <option value="Data Scientist">Data Scientist</option>
                                        <option value="Data Analyst">Data Analyst</option>
                                        <option value="UX Designer">UI/UX Designer</option>
                                        <option value="Business Analyst">Business Analyst</option>
                                        <option value="Marketing">Marketing & Finance</option>
                                        <option value="Other">Other</option>
                                    </select>
                                </div>
                        
                                <!-- Ratings Filter -->
                                <div class="filter-item">
                                    <label for="rating">Rating:</label>
                                    <select id="rating"  onchange="filterIndividualReviews()">
                                        <option value="1">1 Star</option>
                                        <option value="2">2 Stars</option>
                                        <option value="3">3 Stars</option>
                                        <option value="4">4 Stars</option>
                                        <option value="5">5 Stars</option>
                                        <option selected value="all" selected>All</option>
                                    </select>
                                </div>
                        
                                <!-- Time Filter -->
                                <div class="filter-item">
                                    <label for="time-frame">Time Frame:</label>
                                    <select id="time-frame"  onchange="filterIndividualReviews()">
                                        <option value="1-month">Recent 1 Month</option>
                                        <option value="6-months">Recent 6 Months</option>
                                        <option value="1-year">1 Year</option>
                                        <option value="3-years">3 Years</option>
                                        <option selected value="all">All</option>
                                    </select>
                                </div>
                            </div>
                        </div>

                        <!-- Add Review Button -->
                        {% include "jobhub/company_profile/profile_company_reviews.html" %}
                    </div>

                    <h2 class="content-subhead">About JobHub</h2>
                    <p>
                        Welcome to our job application platform, where applicants and employers seamlessly connect. Our user-friendly site simplifies your job search and hiring process, ensuring a smooth journey for all. Discover your next opportunity or talent here with us!                    </p>

                    <div class="pure-g">
                        <div class="pure-u-1-4">
                            <img class="pure-img-responsive"
                                src="http://farm3.staticflickr.com/2875/9069037713_1752f5daeb.jpg" alt="Peyto Lake">
                        </div>
                        <div class="pure-u-1-4">
                            <img class="pure-img-responsive"
                                src="http://farm3.staticflickr.com/2813/9069585985_80da8db54f.jpg" alt="Train">
                        </div>
                        <div class="pure-u-1-4">
                            <img class="pure-img-responsive"
                                src="http://farm6.staticflickr.com/5456/9121446012_c1640e42d0.jpg" alt="T-Shirt Store">
                        </div>
                        <div class="pure-u-1-4">
                            <img class="pure-img-responsive"
                                src="http://farm8.staticflickr.com/7357/9086701425_fda3024927.jpg" alt="Mountain">
                        </div>
                    </div>
                </div>
            </div>
        </div>
    {% endblock %}
</body>

</html>

jobhub/templates/jobhub/base_joblist.html
<!doctype html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title> {% block title %} JobHub {% endblock %} </title>
    {% load static %}
        <link rel="stylesheet" href="{% static 'jobhub/pure-min.css' %}">
        <link rel="stylesheet" href="{% static 'jobhub/style.css' %}">
        <link rel="stylesheet" href="{% static 'jobhub/grids-responsive-min.css' %}">
    {% block additional_static %}
    {% endblock %}
</head>
<body>

<div id="layout" class="content flex-container">

    <div id="nav" class="pure-u">
        <div class="nav-inner">
                {% block menu %}
                {% endblock %}
        </div>
    </div>

    <div id="list" class="pure-u-1">
        {% block list %}
        {% endblock %}
    </div>

    <div id="main" class="pure-u-1">
        <div class="email-content">
            {% block job_main %}
            {% endblock %}
        </div>
    </div>



</div>
{% block filter %}
{% endblock %} 
{% block tools%}
{% endblock %}
{% block popup %}
{% endblock %}
</body>
</html>

jobhub/templates/jobhub/joblist.html
{% extends "jobhub/base_joblist.html" %}

{% block title %} Job List {% endblock %} 

{% load static %}
{% block additional_static %}
    <link rel="stylesheet" href="{% static 'jobhub/joblist_style.css' %}">
    <script src="{% static 'jobhub/joblist.js' %}"></script>
    <script src="{% static 'jobhub/jquery-3.7.1.js' %}"></script>
{% endblock %}

{% block menu %}
    <img width="100" height="100" alt="Tilo Mitra&#x27;s avatar" class="jobhub-avatar" src="/static/jobhub/jobhub.jpg">
    <p style="color: #777;"> {{ request.user.last_name }} account</p>
    <div class="pure-menu">
        <ul class="pure-menu-list">
            <li><a href="{% url 'base_company_profile' %}" class="pure-menu-link">My Profile</a></li>
            <li><a href="{% url 'joblist' %}" class="pure-menu-link">Jobs</a></li>
            <li>
                {% if request.user.last_name == 'employer' %}
                    <a href="{% url 'employer_application' 0 'all' %}" class="pure-menu-link">Applications</a>
                {% else %}
                    <a href="{% url 'applicant_application' 'all' %}" class="pure-menu-link">Applications</a>
                {% endif %}
            </li>
        </ul>
    </div>
    <a href="{% url 'logout' %}" class="pure-menu-link logout-btn">Logout</a>
{% endblock %}

{% block filter %}
    <div class="filter-bar">
        <form id="search-form">
            <div class="search-box">
                <input id="search-input" name="search" type="text" placeholder="🔍Search" />
            </div>
        </form>
        <div class="toggle-button" id="filter-24-hours">
            Past 24 Hours
        </div>
        <div class="toggle-button" id="filter-week">
            Past Week
        </div>
        <div class="toggle-button" id="filter-month">
            Past Month
        </div>
        <div class="toggle-button" id="filter-full-time">
            Full-time job
        </div>
        <div class="toggle-button" id="filter-part-time">
            Part-time job
        </div>
        <div class="toggle-button" id="filter-internship">
            Internship
        </div>
    </div>
{% endblock %}

{% block list %}

{% endblock %}

{% block job_main %}

{% endblock %}

{% block tools%}
    <div class="tools-bar" id="tools-bar">
        <!-- <button class="pure-button" id="save-button"><b>SAVE</b></button> -->
        <button class="pure-button pure-button-primary" id="apply-button" >APPLY</button>
    </div>
{% endblock %}


{% block popup %}
<div id="myModal" class="modal">

        
    <div class="card form-card modal-content" id="submit-window"> 
        <div id="submit-message">
            <h3>Application Submitted.<br> 
                Good luck!</h3>
        </div>

        <button type="button" id="submit-application-cancel">Close</button>
    </div>


</div>
{% endblock %}

jobhub/templates/jobhub/login.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>JobHub</title>
    <link rel="stylesheet" href="/static/jobhub/login_style.css">
    <link rel="stylesheet" href="/static/jobhub/application/application.css">
</head>
<body>
    <header class="header-div" id="id_header_div">
        <h1 class="site-name" id="id_site_name">Job Hub</h1>
        <a class="navigation-links" href= " {% url 'register' %} " id="id_register_link">Register</a>
    </header>
    <main>
        <div id="login-box">
            <form method="post">
                <div class="container">
                    <h1 id="id_page_name">Login</h1>
                    {% if form.non_field_errors %}
                        <div class="errorlist">
                            {{ form.non_field_errors }}
                        </div>
                    {% endif %}
                    <label for="id_username"><b>Username:</b></label>
                    <input type="text" placeholder="Enter Username" name="username" id="id_username" required>
                    <span class="errorlist"> {{ form.username.errors }} </span>

                    <label for="id_password"><b>Password:</b></label>
                    <input type="password" placeholder="Enter Password" name="password" id="id_password" required>
                    <span class="errorlist"> {{ form.username.errors }} </span>
                <button type="submit" class="registerbtn" id="id_login_button">Login</button>
                {% csrf_token %}
            </form>
        </div>
    </main>
</body>
</html>

jobhub/templates/jobhub/register.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>JobHub</title>
    <link rel="stylesheet" href="/static/jobhub/login_style.css">
    <link rel="stylesheet" href="/static/jobhub/application/application.css">
</head>
<body>
    <header class="header-div" id="id_header_div">
        <h1 class="site-name" id="id_site_name">Job Hub</h1>
        <a class="navigation-links" href=" {% url 'login' %} " id="id_login_link">Login</a>
    </header>
    <main>
        <div id="login-box">
            <form method="post">
                <div class="container">
                  <h1>Register</h1>
                  <p>Please fill in this form to create an account.</p>
                  <hr>
                  {% if form.non_field_errors %}
                      <div class="errorlist">
                          {{ form.non_field_errors }}
                      </div>
                  {% endif %}

                  <label for="id_username"><b>Username:</b></label>
                  <input type="text" placeholder="Enter Username" name="username" id="id_username" required>
                  <span class="errorlist"> {{ form.username.errors }} </span>
              
                  <label for="id_password"><b>Password</b></label>
                  <input type="password" placeholder="Enter Password" name="password" id="id_password" required>
                  <span class="errorlist"> {{ form.password.errors }} </span>
              
                  <label for="id_confirm_password"><b>Repeat Password</b></label>
                  <input type="password" placeholder="Repeat Password" name="confirm" id="id_confirm_password" required>
                  <span class="errorlist"> {{ form.confirm.errors }} </span>
                  
                  <label for="id_email"><b>Email</b></label>
                  <input type="text" placeholder="Enter Email" name="email" id="id_email" required>
                  <span class="errorlist"> {{ form.email.errors }} </span>

                  <label for="id_name"><b>User Full name / Company Name:</b></label>
                  <input type="text" placeholder="Enter Name" name="name" id="id_name" required>
                  <span class="errorlist"> {{ form.name.errors }} </span>

                  <label for="type"><b>Account Type:</b></label>
                  <select id="id_type" name="type">
                    <option value="employer">Employer</option>
                    <option value="applicant">Applicant</option>
                  </select>
                  <hr>
                  <p>By creating an account you agree to our Terms & Privacy</a>.</p>
                  <button type="submit" class="registerbtn" id="id_register_button">Register</button>
                </div>
                {% csrf_token %}
              </form>
        </div>
    </main>
</body>
</html>